# ── Base de datos PostgreSQL ─────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/asopistar
spring.datasource.driver-class-name=org.postgresql.Driver
 
# ── JPA / Hibernate ──────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=negocio
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
 
# ── JWT ──────────────────────────────────────────────────────────

jwt.expiration=86400000
 
# ── Servidor ─────────────────────────────────────────────────────
server.port=8080
server.servlet.context-path=/api
 
# ── Logs ─────────────────────────────────────────────────────────
logging.level.org.springframework.security=DEBUG
logging.level.com.config.spring.asopistar=DEBUG

# ── Perfil activo ────────────────────────────────────────────────
spring.profiles.active=dev
